server.port: 8087

spring:
  application.name: landmark-geo-query-engine
  jpa:
    #open-in-view: false
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/landmark_db
    driver-class-name: org.postgresql.Driver
    username: landmark_user
    password: landmark_password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.hibernate.SQL: WARN

# rabbit queue
landmark.request.queue: landmark.request.queue
landmark.response.queue: landmark.response.queue
